import type { Category, Product } from "./types";

/**
 * Static product catalog. This storefront has no database — everything here
 * is hardcoded and shipped with the app.
 */
export const CATEGORIES: Category[] = [
  {
    id: "footwear",
    name: "Footwear",
    slug: "footwear",
    description: "Merino wool runners, trail shoes and slip-ons built to be worn daily.",
    image: "/images/cat-footwear.jpg",
    status: "active",
  },
  {
    id: "apparel",
    name: "Apparel",
    slug: "apparel",
    description: "Knitwear, shells and everyday layers in organic cotton and merino wool.",
    image: "/images/cat-apparel.jpg",
    status: "active",
  },
  {
    id: "accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Canvas totes and caps made to last.",
    image: "/images/cat-accessories.jpg",
    status: "active",
  },
  {
    id: "home-goods",
    name: "Home Goods",
    slug: "home-goods",
    description: "Slow-made essentials for the house — candles, throws and more.",
    image: "/images/cat-home.jpg",
    status: "active",
  },
];

type SeedProduct = Omit<Product, "category" | "category_id"> & { categorySlug: string };

const SEED_PRODUCTS: SeedProduct[] = [
  {
    id: "wool-runner",
    name: "Wool Runner",
    slug: "wool-runner",
    description:
      "Our signature sneaker, knit from ZQ merino wool for a breathable, machine-washable everyday shoe.",
    price_cents: 9800,
    images: ["/images/wool-runner.jpg"],
    tags: ["Merino Wool", "Everyday", "Unisex", "Sneaker"],
    inventory: 42,
    status: "active",
    featured: true,
    sales_count: 1240,
    created_at: "2026-06-01T00:00:00.000Z",
    categorySlug: "footwear",
  },
  {
    id: "trail-shoe",
    name: "Trail Shoe",
    slug: "trail-shoe",
    description: "A rugged, all-terrain shoe with a recycled-cotton upper and grippy tread.",
    price_cents: 12800,
    images: ["/images/trail-shoe.jpg"],
    tags: ["Trail", "Recycled Cotton", "Outdoor"],
    inventory: 27,
    status: "active",
    featured: true,
    sales_count: 610,
    created_at: "2026-05-20T00:00:00.000Z",
    categorySlug: "footwear",
  },
  {
    id: "canvas-sneaker",
    name: "Canvas Sneaker",
    slug: "canvas-sneaker",
    description: "A classic low-top in organic cotton canvas with a natural rubber sole.",
    price_cents: 8800,
    images: ["/images/canvas-sneaker.jpg"],
    tags: ["Organic Cotton", "Classic", "Low-Top"],
    inventory: 35,
    status: "active",
    featured: false,
    sales_count: 480,
    created_at: "2026-05-10T00:00:00.000Z",
    categorySlug: "footwear",
  },
  {
    id: "slip-on",
    name: "Slip-On",
    slug: "slip-on",
    description: "Laceless and lightweight, made from tree-fibre knit for warm-weather wear.",
    price_cents: 9200,
    images: ["/images/slip-on.jpg"],
    tags: ["Tree Fibre", "Laceless", "Lightweight"],
    inventory: 30,
    status: "active",
    featured: false,
    sales_count: 350,
    created_at: "2026-04-28T00:00:00.000Z",
    categorySlug: "footwear",
  },
  {
    id: "knit-sweater",
    name: "Merino Knit Sweater",
    slug: "merino-knit-sweater",
    description: "A midweight crewneck knit from responsibly-sourced merino wool.",
    price_cents: 14800,
    images: ["/images/knit-sweater.jpg"],
    tags: ["Merino Wool", "Crewneck", "Midweight"],
    inventory: 22,
    status: "active",
    featured: true,
    sales_count: 390,
    created_at: "2026-06-05T00:00:00.000Z",
    categorySlug: "apparel",
  },
  {
    id: "jacket",
    name: "Shell Jacket",
    slug: "shell-jacket",
    description: "A packable, weather-resistant shell made from recycled nylon.",
    price_cents: 19800,
    images: ["/images/jacket.jpg"],
    tags: ["Recycled Nylon", "Packable", "Weather-Resistant"],
    inventory: 18,
    status: "active",
    featured: true,
    sales_count: 260,
    created_at: "2026-05-15T00:00:00.000Z",
    categorySlug: "apparel",
  },
  {
    id: "tee",
    name: "Organic Cotton Tee",
    slug: "organic-cotton-tee",
    description: "A heavyweight tee cut from 100% organic cotton jersey.",
    price_cents: 3800,
    images: ["/images/tee.jpg"],
    tags: ["Organic Cotton", "Heavyweight", "Everyday"],
    inventory: 60,
    status: "active",
    featured: false,
    sales_count: 820,
    created_at: "2026-04-02T00:00:00.000Z",
    categorySlug: "apparel",
  },
  {
    id: "socks",
    name: "Wool Crew Socks",
    slug: "wool-crew-socks",
    description: "Cushioned crew socks knit from merino wool, sold as a set of three.",
    price_cents: 2400,
    images: ["/images/socks.jpg"],
    tags: ["Merino Wool", "Crew", "Set of 3"],
    inventory: 80,
    status: "active",
    featured: false,
    sales_count: 950,
    created_at: "2026-03-18T00:00:00.000Z",
    categorySlug: "apparel",
  },
  {
    id: "cap",
    name: "Canvas Cap",
    slug: "canvas-cap",
    description: "A five-panel cap in heavyweight organic cotton canvas.",
    price_cents: 3400,
    images: ["/images/cap.jpg"],
    tags: ["Organic Cotton", "Five-Panel"],
    inventory: 45,
    status: "active",
    featured: false,
    sales_count: 300,
    created_at: "2026-03-01T00:00:00.000Z",
    categorySlug: "accessories",
  },
  {
    id: "tote",
    name: "Canvas Tote",
    slug: "canvas-tote",
    description: "A roomy, durable tote made from heavyweight organic cotton canvas.",
    price_cents: 4200,
    images: ["/images/tote.jpg"],
    tags: ["Organic Cotton", "Everyday Carry"],
    inventory: 50,
    status: "active",
    featured: true,
    sales_count: 540,
    created_at: "2026-06-10T00:00:00.000Z",
    categorySlug: "accessories",
  },
  {
    id: "candle",
    name: "Soy Candle",
    slug: "soy-candle",
    description: "A slow-burning soy wax candle, hand-poured with a cedar and fig scent.",
    price_cents: 3200,
    images: ["/images/candle.jpg"],
    tags: ["Soy Wax", "Hand-Poured", "Home"],
    inventory: 70,
    status: "active",
    featured: false,
    sales_count: 410,
    created_at: "2026-02-14T00:00:00.000Z",
    categorySlug: "home-goods",
  },
  {
    id: "throw-blanket",
    name: "Wool Throw Blanket",
    slug: "wool-throw-blanket",
    description: "A woven throw blanket in undyed merino wool, made to last generations.",
    price_cents: 8800,
    images: ["/images/throw-blanket.jpg"],
    tags: ["Merino Wool", "Undyed", "Home"],
    inventory: 25,
    status: "active",
    featured: false,
    sales_count: 190,
    created_at: "2026-01-25T00:00:00.000Z",
    categorySlug: "home-goods",
  },
];

const categoryBySlug = new Map(CATEGORIES.map((c) => [c.slug, c]));

export const PRODUCTS: Product[] = SEED_PRODUCTS.map(({ categorySlug, ...product }) => {
  const category = categoryBySlug.get(categorySlug) ?? null;
  return {
    ...product,
    category_id: category?.id ?? null,
    category: category ? { name: category.name, slug: category.slug } : null,
  };
});
